[tool.black]
target-version = ["py38", "py39"]
color = true
skip_magic_trailing_comma = true
exclude = '''
/(
    | data
    | logo
    | logs
    | lightning_logs
    | output
    # Python
    | build
    | dist
    | \.cache
    | \.mypy_cache
    | \.pytest_cache
    |  __pycache__
    | .*\.egg-info
    # Git
    | \.git
    | \.github
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["tests", "detcon"]
extend_skip = ["data", "logs", "lightning_logs"]
skip_gitignore = true
color_output = true

[tool.pytest.ini_options]
# Skip slow tests by default
addopts = "-m 'not slow'"
filterwarnings = [
    "ignore:.*Create unlinked descriptors is going to go away.*:DeprecationWarning",
    # https://github.com/tensorflow/tensorboard/pull/5138
    "ignore:.*is a deprecated alias for the builtin.*:DeprecationWarning",
]
markers = [
    "slow: marks tests as slow",
]
norecursedirs = [
    ".ipynb_checkpoints",
    "data",
    "__pycache__",
]
testpaths = [
    "tests",
]