module:
    backbone: vit_small
    pretrained: False
    num_classes: 21
    num_samples: 5
    downsample: 16
    proj_hidden_dim: 128
    proj_dim: 256

datamodule:
    root: /mnt/e/data/
    batch_size: 80
    num_workers: 18
    prefetch_factor: 2

trainer:
    max_epochs: 5
    precision: 16
    gpus: 1
    log_every_n_steps: 25
